import{a as F,S as B,i}from"./assets/vendor-BAQQTdrx.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const s of r.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function l(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=l(e);fetch(e.href,r)}})();const M="55675951-c5be5de1598e9491b9f323a37",$="https://pixabay.com/api/";async function h(t,o){return{data:(await F.get($,{params:{key:M,q:t,page:o,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data,perPage:15}}const d=document.querySelector(".gallery"),u=document.querySelector(".loader-overlay"),f=document.querySelector(".load-more"),k=new B(".gallery a",{captionsData:"alt",captionDelay:250});function v(t){if(!d)return;const o=t.map(({largeImageURL:l,webformatURL:a,tags:e,likes:r,views:s,comments:q,downloads:P})=>`
      <li class="gallery-card">
        <a class="gallery-link" href="${l}">
          <img class="gallery-image" src="${a}" alt="${e}" />
        </a>
      <div class="card-info">
        <div class="info-block"><span class="info-label">Likes</span><span class="info-value">${r}</span></div>
        <div class="info-block"><span class="info-label">Views</span><span class="info-value">${s}</span></div>
        <div class="info-block"><span class="info-label">Comments</span><span class="info-value">${q}</span></div>
        <div class="info-block"><span class="info-label">Downloads</span><span class="info-value">${P}</span></div>
      </div>
    </li>`).join("");d.insertAdjacentHTML("beforeend",o),k.refresh()}function O(){d&&(d.innerHTML="")}function b(){u&&u.classList.add("is-active")}function L(){u&&u.classList.remove("is-active")}function R(){f&&f.classList.remove("is-hidden")}function g(){f&&f.classList.add("is-hidden")}const m=document.querySelector(".form"),y=document.querySelector(".load-more");let c="",n=1,p=0,w=0;m.addEventListener("submit",async t=>{if(t.preventDefault(),c=t.currentTarget.elements.query.value.trim(),n=1,c===""){i.warning({message:"Please enter search query",position:"topRight"});return}O(),g(),b();try{const o=await h(c,n);if(p=o.data.totalHits,w=o.perPage,o.data.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. <br> Please try again!",position:"topRight",backgroundColor:"rgba(239, 64, 64, 0.8)",messageColor:"#FFF",iconColor:"#FFFFFF",theme:"dark"});return}v(o.data.hits),S()}catch(o){i.error({message:"Something went wrong!",position:"topRight"}),console.error(o)}finally{L(),m.reset()}});y&&y.addEventListener("click",async()=>{n+=1,b(),g();try{const t=await h(c,n);v(t.data.hits),_(),S()}catch(t){i.error({message:"Error loading more images!",position:"topRight"}),console.error(t)}finally{L()}});function S(){const t=Math.ceil(p/w);n>=t?(g(),p>0&&i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):R()}function _(){const t=document.querySelector(".gallery-card");if(t){const{height:o}=t.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
