import{a as F,S as $,i as n}from"./assets/vendor-BAQQTdrx.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))l(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const i of s.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&l(i)}).observe(document,{childList:!0,subtree:!0});function c(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function l(t){if(t.ep)return;t.ep=!0;const s=c(t);fetch(t.href,s)}})();const B="55675951-c5be5de1598e9491b9f323a37",M="https://pixabay.com/api/",h=15;async function L(e,o){return(await F.get(M,{params:{key:B,q:e,page:o,per_page:h,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const f=document.querySelector(".gallery"),p=document.querySelector(".loader-overlay"),m=document.querySelector(".load-more"),T=new $(".gallery a",{captionsData:"alt",captionDelay:250});function b(e){if(!f)return;const o=e.map(({largeImageURL:c,webformatURL:l,tags:t,likes:s,views:i,comments:k,downloads:E})=>`
      <li class="gallery-card">
        <a class="gallery-link" href="${c}">
          <img class="gallery-image" src="${l}" alt="${t}" />
        </a>
      <div class="card-info">
        <div class="info-block"><span class="info-label">Likes</span><span class="info-value">${s}</span></div>
        <div class="info-block"><span class="info-label">Views</span><span class="info-value">${i}</span></div>
        <div class="info-block"><span class="info-label">Comments</span><span class="info-value">${k}</span></div>
        <div class="info-block"><span class="info-label">Downloads</span><span class="info-value">${E}</span></div>
      </div>
    </li>`).join("");f.insertAdjacentHTML("beforeend",o),T.refresh()}function C(){f&&(f.innerHTML="")}function w(){p&&p.classList.add("is-active")}function S(){p&&p.classList.remove("is-active")}function R(){m&&m.classList.remove("is-hidden")}function y(){m&&m.classList.add("is-hidden")}const O=document.querySelector(".form"),v=document.querySelector(".load-more"),d=document.querySelector(".images-counter");let u="",r=1,a=0;O.addEventListener("submit",async e=>{if(e.preventDefault(),u=e.currentTarget.elements.query.value.trim(),r=1,u===""){n.warning({message:"Please enter search query",position:"topRight"});return}C(),d.classList.add("is-hidden"),y(),w();try{const o=await L(u,r);if(a=o.totalHits,o.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. <br> Please try again!",position:"topRight",backgroundColor:"rgba(239, 64, 64, 0.8)",messageColor:"#FFF",iconColor:"#FFFFFF",theme:"dark"});return}b(o.hits),P(),q()}catch{n.error({message:"Something went wrong!",position:"topRight"})}finally{S()}});v&&v.addEventListener("click",async()=>{r+=1,w(),y();try{const e=await L(u,r);b(e.hits),P(),x(),q()}catch{n.error({message:"Error loading more images!",position:"topRight"})}finally{S()}});function q(){const e=Math.ceil(a/h);r>=e?(y(),a>0&&n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):R()}function x(){const e=document.querySelector(".gallery-card");if(e){const{height:o}=e.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}}function P(){const e=Math.min(r*h,a);a>0?(d.textContent=`${e} of ${a}`,d.classList.remove("is-hidden")):d.classList.add("is-hidden")}const g=document.querySelector("#backToTop");window.addEventListener("scroll",()=>{window.scrollY>600?g.classList.remove("is-hidden"):g.classList.add("is-hidden")});g.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})});
//# sourceMappingURL=index.js.map
